[package]
name = "async-basics"
version = "0.1.0"
authors = ["Kamran Jabbar <kamranajabbar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1"
surf = "1"
serde = "1.0.114"
